### ISSUE TITLE
Using this (or newer version on pferrel) with Swift 2.0

### ISSUE THREAD

**Issue by anthonyemberley** [minhtule/PredictionIO-Swift-SDK-DEPRECATED#1]
Hi,

I am wondering if there are any plans to update the PredictionIOSDK for swift to be compatible with Xcode 7 and Swift 2.0.  Currently it is impossible to use PredictionIO with the newer version of Swift.

Thanks!

Anthony

**Comment by zhongmin2015** [comment]
Hi,
Now I use the xcode7 version, but can not use pod to import your SDK what method can you normally import your SDK? .

Thanks!
zhong

**Comment by minhtule** [comment]
Hi, I'm so sorry for the long overdue reply. I've rewritten the SDK in Swift 4.0 in this new repo https://github.com/minhtule/PredictionIO-Swift-SDK.
